### ISSUE TITLE
Header 补完计划。

### ISSUE THREAD

**Issue by lychees** [Andoromeda-Foundation/Happyeos21pt#1]
- [x] 游戏类别改成下拉选框。([Element UI Dropdown](http://element-cn.eleme.io/#/zh-CN/component/dropdown))
- [x] 网络类型改成下拉选框。(同上)
- [x] 语言改成下拉选框，并增加日语。(Done in PR #10 )
- [x] 登陆放在 Header 中。(Done in PR #11 )
- [x] 引入 vue-router（Done in PR #14 )

**Comment by frankwei98** [comment]
All Done.
